[project]
name = "py-yt-downloader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "inquirer>=3.4.1",
    "pyinstaller>=6.20.0",
    "pytubefix>=10.4.0",
    "requests>=2.33.1",
    "simple-chalk>=0.1.0",
    "tqdm>=4.67.3",
    "uuid>=1.30",
]
